### ISSUE TITLE
How to install/run the application

### ISSUE THREAD

**Issue by jgsogo** [carpanla/sudoku#9]
After `npm install` I run `npm start`, but it fails with this error:

![image](https://user-images.githubusercontent.com/1406456/71822692-d03adb80-3095-11ea-80f4-f31ae0ce8783.png)

I need to run `npm install node-sass` too in order for it to work. It should be added to the _install instructions_ in the README.

**Comment by jgsogo** [comment]
Don't close an issue without writing a reason. In this case, as you have added the needed changes to the PR #8 in 77fe10cb768200c1260bd082a91196849ff4edc0, you should:
 * comment here about that (but don't close this issue)
 * modify the description of the PR #8 to account for these changes 
 * add a `closes #9` text to the description of #8 that will close this issue when that PR is merged into the main branch (best Github magic ever). Yes, this issue is not fixed until the PR is merged.

   
   ![image](https://user-images.githubusercontent.com/1406456/71920575-571bb100-3187-11ea-9444-fd44048887b6.png)

**Comment by carpanla** [comment]
Solucionado en pull request #8.
